### ISSUE TITLE
not getting the exact rectangular box i need.

### ISSUE THREAD

**Issue by ganeshsingamaneni** [KananVyas/BoxDetection#1]
its working for me for some images and not working for all 

here in the image it may have one circle shape and two or three rectangle boxes and in that three i need the bigger one.

if there is only one rectangle its getting but when there is two or more it giving another rectangle of different size.

**Comment by KananVyas** [comment]
You should try to change with horizontel and vertical kernel length. Change the dilation and erosion iterations if needed.
